name: Update README with New Content

#on:
#  schedule:
#    # Runs at 00:00 UTC every Sunday
#    - cron: '0 0 * * 0'

on: [push]

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Clone Second Repository
        run: git clone https://github.com/localstack/docs.git

      - name: Check for New Tutorials and Update README
        run: |
          cd docs/content/en/tutorials/
          
          tutorials_section="\n"

          for folder in */; do
            folder_name=${folder%/}
            title=$(grep '^title:' "$folder/index.md" | sed 's/title: //')
            tutorials_section+="- [$title](https://docs.localstack.cloud/tutorials/$folder_name)\n"
          
          done
  
          awk -v new_content="$tutorials_section" '/^## Tutorials/{print;getline;print new_content;next} /^## Blog Posts/{exit}1' ../../../../README.md > temp.md && mv temp.md ../../../../README.md

      - name: Commit and Push Changes
        run: |
          git config --global user.name 'AncaGhenade'
          git config --global user.email 'ancaghenade@gmail.com'
          git add README.md
          git commit -m "Update README with new tutorials"
          git push
